version: '3.0'

services:
  app:
      image: evanng1/ezweb
      container_name: ezweb
      restart: always
      volumes:
        - ./conf/php.ini:/usr/local/etc/php/conf.d/app.ini
        - ./conf/apache.conf:/etc/apache2/conf-available/z-app.conf
        - ./conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
        - ./app:/app
      ports:
        - 8080:80